create table books (
  id bigint generated by default as identity primary key,
  isbn varchar(20) not null unique,
  title varchar(255) not null,
  author varchar(255) not null,
  price decimal(10,2) not null,
  version bigint not null default 0
);
